const EX = {
  mars: { name: 'Marcheren met hoge knieën', kind: 'time', muscles: 'Conditie, heupen, buik',
    steps: ['Sta rechtop met je buik licht aangespannen.', 'Til afwisselend je knieën op tot ongeveer heuphoogte.', 'Zwaai je armen actief mee, ellebogen in een hoek van 90°.', 'Hoger tempo = zwaarder. Blijf rustig doorademen.'],
    tip: 'Land zacht op je voorvoet, niet op je hielen.', jump: 'High knees (rennend op de plaats)', q: 'high knees march low impact' },
  stepjack: { name: 'Step jacks', kind: 'time', muscles: 'Conditie, schouders, benen',
    steps: ['Start met je voeten bij elkaar en armen langs je lichaam.', 'Stap met één voet opzij en zwaai tegelijk je armen boven je hoofd.', 'Stap terug en laat je armen zakken.', 'Wissel steeds van kant en zoek een lekker ritme.'],
    tip: 'Hetzelfde als een jumping jack, maar zonder springen.', jump: 'Jumping jacks', q: 'step jack low impact jumping jack' },
  boksen: { name: 'Boksen (stoten)', kind: 'time', muscles: 'Conditie, schouders, armen, buik',
    steps: ['Sta in een lichte spreidstand, knieën zacht, vuisten bij je kin.', 'Stoot afwisselend links en rechts recht naar voren.', 'Draai je romp en achterste voet licht mee bij elke stoot.', 'Trek je vuist na elke stoot direct terug naar je kin.'],
    tip: 'Strek je arm niet helemaal op slot; houd je ellebogen soepel.', q: 'shadow boxing workout beginner' },
  skater: { name: 'Schaatsstap', kind: 'time', muscles: 'Conditie, billen, benen',
    steps: ['Stap met je rechterbeen schuin naar achteren, achter je linkerbeen langs.', 'Buig je linkerknie licht en zwaai je armen mee naar links.', 'Kom terug en doe hetzelfde naar de andere kant.', 'Maak het vloeiend, als een schaatser.'],
    tip: 'Houd je knie in lijn met je tenen.', jump: 'Skater hops (zijwaarts springen)', q: 'low impact skater exercise' },
  kniecross: { name: 'Knie naar elleboog (staand)', kind: 'time', muscles: 'Buik, schuine buikspieren, conditie',
    steps: ['Sta rechtop met je vingertoppen licht achter je oren.', 'Til je rechterknie diagonaal op naar je linkerelleboog.', 'Zet je voet terug en wissel van kant.', 'Span je buik aan bij elke beweging.'],
    tip: 'Trek niet aan je hoofd; de beweging komt uit je buik.', q: 'standing cross body knee to elbow' },
  hakbil: { name: 'Hakken naar billen', kind: 'time', muscles: 'Conditie, achterkant bovenbeen',
    steps: ['Loop op de plaats.', 'Breng bij elke stap je hak richting je billen.', 'Houd je knieën onder je heupen.', 'Zwaai je armen mee.'],
    tip: 'Begin rustig en voer het tempo langzaam op.', jump: 'Butt kicks (rennend)', q: 'butt kicks low impact' },
  squatreach: { name: 'Squat met reik omhoog', kind: 'time', muscles: 'Benen, billen, conditie',
    steps: ['Voeten iets breder dan heupbreed.', 'Zak rustig in een squat, armen naar voren.', 'Kom omhoog en reik met beide armen naar het plafond, eventueel op je tenen.', 'Direct door naar de volgende herhaling.'],
    tip: 'Borst omhoog, knieën in lijn met je tenen.', jump: 'Jump squat', q: 'squat to overhead reach' },
  shuffle: { name: 'Zijwaartse shuffle', kind: 'time', muscles: 'Conditie, benen, billen',
    steps: ['Zak licht door je knieën, borst omhoog.', 'Neem drie snelle zijstapjes naar rechts.', 'Neem drie stapjes terug naar links.', 'Blijf laag en licht op je voeten.'],
    tip: 'Laat je voeten niet kruisen.', q: 'lateral shuffle exercise' },
  trede: { name: 'Traptrede op en af', kind: 'time', muscles: 'Conditie, benen, billen',
    steps: ['Ga voor de onderste traptrede staan, houd de leuning vast.', 'Stap op de trede met je rechtervoet, zet je linkervoet erbij.', 'Stap weer af, rechts eerst.', 'Wissel halverwege van leidend been.'],
    tip: 'Zet je hele voet op de trede.', q: 'step ups on stairs cardio' },
  voetjes: { name: 'Snelle voetjes', kind: 'time', muscles: 'Conditie, kuiten',
    steps: ['Sta met je voeten heupbreed, knieën licht gebogen.', 'Trappel zo snel als je kunt met kleine pasjes op je voorvoeten.', 'Houd je bovenlichaam stil en rechtop.', 'Beweeg je armen mee.'],
    tip: 'Klein en snel is beter dan groot en langzaam.', q: 'fast feet drill exercise' },
  armcirkel: { name: 'Armcirkels', kind: 'time', muscles: 'Schouders (warming-up)',
    steps: ['Strek je armen opzij.', 'Maak kleine cirkels en maak ze langzaam groter.', 'Halverwege de andere kant op draaien.'],
    tip: 'Rustig en gecontroleerd.', q: 'arm circles warm up' },
  heupcirkel: { name: 'Heupcirkels', kind: 'time', muscles: 'Heupen, onderrug (warming-up)',
    steps: ['Handen in je zij, voeten heupbreed.', 'Draai grote, rustige cirkels met je heupen.', 'Halverwege de andere kant op.'],
    tip: 'Houd je bovenlichaam zo stil mogelijk.', q: 'hip circles warm up' },
  beenzwaai: { name: 'Been zwaaien', kind: 'time', muscles: 'Heupen (warming-up)', side: true,
    steps: ['Houd een muur of stoel vast.', 'Zwaai één been ontspannen naar voren en naar achteren.', 'Na de helft van de tijd: ander been.'],
    tip: 'Zwaai niet hoger dan comfortabel voelt.', q: 'leg swings warm up' },
  squat: { name: 'Squat', kind: 'reps', dbOpt: true, muscles: 'Benen, billen',
    steps: ['Voeten heupbreed tot iets breder, tenen licht naar buiten.', 'Zak rustig alsof je op een stoel gaat zitten, borst omhoog.', 'Ga zo diep als comfortabel voelt, ongeveer tot je dijen horizontaal zijn.', 'Duw via je hielen terug omhoog.', 'Met een dumbbell: houd hem rechtop voor je borst (goblet squat).'],
    tip: 'Knieën wijzen dezelfde kant op als je tenen.', q: 'goblet squat form beginner' },
  sumo: { name: 'Sumo squat', kind: 'reps', dbOpt: true, muscles: 'Binnenkant bovenbeen, billen',
    steps: ['Brede stand, tenen schuin naar buiten.', 'Houd een dumbbell met beide handen tussen je benen (of handen voor je borst).', 'Zak recht naar beneden, knieën naar buiten.', 'Kom omhoog en knijp je billen aan.'],
    tip: 'Houd je rug recht en je borst omhoog.', q: 'dumbbell sumo squat' },
  lunge: { name: 'Achterwaartse lunge', kind: 'reps', side: true, dbOpt: true, muscles: 'Benen, billen',
    steps: ['Sta rechtop; houd eventueel een stoel vast voor balans.', 'Stap met één been een grote stap naar achteren.', 'Zak tot beide knieën ongeveer 90° gebogen zijn, achterste knie net boven de grond.', 'Duw via de hiel van je voorste been terug.', 'Doe alle herhalingen per kant.'],
    tip: 'Voorste knie blijft boven je enkel.', q: 'reverse lunge beginner form' },
  bridge: { name: 'Bilbrug', kind: 'reps', dbOpt: true, muscles: 'Billen, achterkant bovenbeen',
    steps: ['Lig op je rug, voeten plat en heupbreed, dicht bij je billen.', 'Armen naast je lichaam, handpalmen plat op de grond.', 'Duw je heupen omhoog tot knie, heup en schouder op één lijn.', 'Knijp je billen 1 seconde aan en zak rustig terug.', 'Met dumbbell: leg hem op je heupen en houd hem vast.'],
    tip: 'Trek je rug niet hol; de kracht komt uit je billen.', q: 'glute bridge form' },
  kuit: { name: 'Kuitheffen', kind: 'reps', dbOpt: true, muscles: 'Kuiten',
    steps: ['Sta rechtop, houd eventueel een muur vast.', 'Kom zo hoog mogelijk op je tenen.', 'Houd 1 seconde vast en zak langzaam terug.'],
    tip: 'Langzaam zakken maakt het effectiever.', q: 'standing calf raise' },
  zijbeen: { name: 'Zijlig been heffen', kind: 'reps', side: true, muscles: 'Buitenkant heup, billen',
    steps: ['Lig op je zij, hoofd rustend op je onderste arm.', 'Onderste been licht gebogen, bovenste been gestrekt.', 'Til je bovenste been rustig op tot heuphoogte of iets hoger.', 'Laat langzaam zakken. Alle herhalingen, dan andere kant.'],
    tip: 'Tenen wijzen naar voren, niet naar het plafond.', q: 'side lying leg raise' },
  clam: { name: 'Clamshell', kind: 'reps', side: true, muscles: 'Billen, heupen',
    steps: ['Lig op je zij met gebogen knieën, voeten op elkaar.', 'Houd je voeten tegen elkaar en open je bovenste knie als een schelp.', 'Sluit weer rustig.', 'Alle herhalingen, dan de andere kant.'],
    tip: 'Rol je heup niet naar achteren mee.', q: 'clamshell exercise' },
  deadbug: { name: 'Dead bug', kind: 'reps', muscles: 'Buik, rompstabiliteit',
    steps: ['Lig op je rug, armen recht omhoog, knieën 90° boven je heupen.', 'Druk je onderrug zacht tegen de vloer.', 'Strek langzaam je rechterarm naar achteren en je linkerbeen naar voren.', 'Terug naar het midden en wissel. Elke kant telt als één herhaling.'],
    tip: 'Komt je onderrug los van de vloer? Maak de beweging kleiner.', q: 'dead bug exercise beginner' },
  heeltaps: { name: 'Hielen tikken', kind: 'reps', muscles: 'Schuine buikspieren',
    steps: ['Lig op je rug, knieën gebogen, voeten plat.', 'Til je schouders een klein stukje van de vloer.', 'Reik met je rechterhand naar je rechterhiel, dan links naar links.', 'Elke tik telt als één herhaling.'],
    tip: 'Kijk schuin omhoog; houd je nek ontspannen.', q: 'heel taps ab exercise' },
  zijplank: { name: 'Zijplank op knie en onderarm', kind: 'time', side: true, muscles: 'Schuine buikspieren, romp',
    steps: ['Lig op je zij, steun op je onderarm met je elleboog onder je schouder.', 'Knieën gebogen, onderste knie op de grond.', 'Til je heupen op tot een rechte lijn van knie tot hoofd.', 'Houd vast, dan de andere kant.'],
    tip: 'Je steunt op je onderarm, niet op je hand of pols.', q: 'modified side plank on knees' },
  wallsit: { name: 'Muurzit (wall sit)', kind: 'time', muscles: 'Bovenbenen, billen',
    steps: ['Leun met je rug tegen een muur.', 'Schuif naar beneden tot je knieën ongeveer 90° gebogen zijn (of minder diep).', 'Knieën boven je enkels, armen ontspannen.', 'Houd vast en adem rustig door.'],
    tip: 'Minder diep zakken is prima als je net begint.', q: 'wall sit form' },
  curl: { name: 'Biceps curl', kind: 'reps', db: true, muscles: 'Biceps',
    steps: ['Sta rechtop met een dumbbell in elke hand, handpalmen naar voren.', 'Houd je ellebogen dicht bij je lichaam.', 'Buig je armen en breng de dumbbells naar je schouders.', 'Laat langzaam zakken.'],
    tip: 'Niet zwaaien met je lichaam.', q: 'dumbbell bicep curl form' },
  press: { name: 'Schouderpress', kind: 'reps', db: true, muscles: 'Schouders, triceps',
    steps: ['Zit rechtop op een stoel of sta met je buik aangespannen.', 'Dumbbells op schouderhoogte, handpalmen naar voren.', 'Duw de dumbbells omhoog tot je armen bijna gestrekt zijn.', 'Laat gecontroleerd zakken.'],
    tip: 'Trek je rug niet hol; zittend is extra rugvriendelijk.', q: 'seated dumbbell shoulder press beginner' },
  lateral: { name: 'Zijwaarts heffen', kind: 'reps', db: true, muscles: 'Schouders',
    steps: ['Sta rechtop met een dumbbell in elke hand langs je lichaam.', 'Ellebogen licht gebogen.', 'Til je armen opzij tot schouderhoogte.', 'Laat langzaam zakken.'],
    tip: 'Schouders laag houden, weg van je oren.', q: 'dumbbell lateral raise form' },
  triceps: { name: 'Triceps boven het hoofd', kind: 'reps', db: true, muscles: 'Achterkant bovenarm',
    steps: ['Zit of sta rechtop en houd één dumbbell met beide handen vast.', 'Breng hem met gestrekte armen boven je hoofd.', 'Buig je ellebogen en laat de dumbbell achter je hoofd zakken.', 'Strek je armen weer.'],
    tip: 'Ellebogen wijzen naar voren, dicht bij je hoofd.', q: 'overhead dumbbell tricep extension' },
  pullover: { name: 'Pull-over liggend', kind: 'reps', db: true, muscles: 'Rug (brede rugspier), borst',
    steps: ['Lig op je rug, knieën gebogen, voeten plat.', 'Houd één dumbbell met beide handen boven je borst, armen licht gebogen.', 'Breng de dumbbell rustig naar achteren boven je hoofd, zo ver als comfortabel.', 'Trek hem terug boven je borst.'],
    tip: 'Houd je onderrug tegen de vloer; je rug ligt volledig gesteund.', q: 'dumbbell pullover on floor' },
  floorpress: { name: 'Borstpress liggend', kind: 'reps', db: true, muscles: 'Borst, triceps',
    steps: ['Lig op je rug, knieën gebogen, dumbbell in elke hand.', 'Bovenarmen op de grond, ellebogen schuin naar buiten.', 'Duw de dumbbells omhoog boven je borst.', 'Laat rustig zakken tot je bovenarmen de grond raken.'],
    tip: 'Polsen recht boven je ellebogen houden.', q: 'dumbbell floor press' },
  str_quad: { name: 'Stretch voorkant bovenbeen', kind: 'time', side: true, muscles: 'Cooling-down',
    steps: ['Houd een muur vast.', 'Pak je enkel en breng je hak richting je billen.', 'Knieën naast elkaar, heup naar voren.', 'Halverwege wisselen.'], tip: 'Rustig ademen, niet verend stretchen.', q: 'standing quad stretch' },
  str_ham: { name: 'Stretch achterkant bovenbeen', kind: 'time', side: true, muscles: 'Cooling-down',
    steps: ['Zet één hiel iets naar voren, tenen omhoog.', 'Buig je andere knie en duw je billen naar achteren.', 'Houd je rug recht; handen op je bovenbeen.', 'Halverwege wisselen.'], tip: 'Je voelt het aan de achterkant van je gestrekte been.', q: 'standing hamstring stretch' },
  str_kuit: { name: 'Kuitstretch tegen de muur', kind: 'time', side: true, muscles: 'Cooling-down',
    steps: ['Handen tegen de muur, één been naar achteren.', 'Achterste hiel op de grond, voorste knie gebogen.', 'Leun licht naar voren.', 'Halverwege wisselen.'], tip: 'Tenen wijzen naar de muur.', q: 'calf stretch wall' },
  str_bil: { name: 'Bilstretch liggend (figuur 4)', kind: 'time', side: true, muscles: 'Cooling-down',
    steps: ['Lig op je rug met gebogen knieën.', 'Leg je rechterenkel op je linkerknie.', 'Trek je linkerbeen rustig naar je toe.', 'Halverwege wisselen.'], tip: 'Hoofd blijft op de grond.', q: 'supine figure four stretch' },
  str_schouder: { name: 'Schouderstretch', kind: 'time', muscles: 'Cooling-down',
    steps: ['Breng één arm gestrekt voor je borst langs.', 'Druk hem zacht aan met je andere onderarm.', 'Halverwege wisselen.'], tip: 'Schouders laag.', q: 'cross body shoulder stretch' },
  adem: { name: 'Rustig ademen', kind: 'time', muscles: 'Cooling-down',
    steps: ['Sta of lig ontspannen.', 'Adem 4 tellen in door je neus.', 'Adem 6 tellen uit door je mond.'], tip: 'Voel je hartslag rustig zakken.', q: 'breathing cool down exercise' },
  uitlopen: { name: 'Rustig op de plaats lopen', kind: 'time', muscles: 'Afkoelen',
    steps: ['Loop rustig op de plaats of door de kamer.', 'Laat je armen losjes meezwaaien.', 'Adem rustig en laat je hartslag zakken.'], tip: 'Niet abrupt stoppen na een pittige training.', q: 'cool down walking in place' },
  zijtik: { name: 'Zijwaartse teentik', kind: 'time', muscles: 'Conditie, benen',
    steps: ['Sta rechtop, knieën zacht.', 'Stap met je rechtervoet opzij en tik met je teen de grond aan.', 'Terug naar het midden en wissel naar links.', 'Zwaai je armen mee en voer het tempo op.'], tip: 'Rustige variant voor knieën en heupen.', q: 'side step toe tap cardio' },
  zijcrunch: { name: 'Staande zijwaartse crunch', kind: 'reps', side: true, muscles: 'Schuine buikspieren',
    steps: ['Sta met je voeten heupbreed, vingertoppen achter je oren.', 'Til je rechterknie opzij omhoog en breng je rechterelleboog ernaartoe.', 'Zet je voet terug.', 'Alle herhalingen, dan de andere kant.'], tip: 'Houd je rug recht; buig vanuit je zij.', q: 'standing side crunch' },
  stoelsquat: { name: 'Opstaan van een stoel', kind: 'reps', dbOpt: true, muscles: 'Benen, billen',
    steps: ['Ga op het randje van een stevige stoel zitten, voeten heupbreed.', 'Leun licht voorover en sta op door je hielen in de grond te duwen.', 'Ga rustig en gecontroleerd weer zitten.', 'Met dumbbell: houd hem voor je borst.'], tip: 'Kniesparend alternatief voor de squat.', q: 'sit to stand exercise chair squat' },
  splitsquat: { name: 'Split squat', kind: 'reps', side: true, dbOpt: true, muscles: 'Benen, billen',
    steps: ['Zet één voet een grote pas naar voren; houd eventueel een stoel vast.', 'Zak recht naar beneden tot je achterste knie net boven de grond is.', 'Duw via je voorste hiel omhoog; je voeten blijven staan.', 'Alle herhalingen, dan de andere kant.'], tip: 'Stabieler dan een lunge omdat je niet stapt.', q: 'split squat beginner' },
  stepup: { name: 'Step-up op de traptrede', kind: 'reps', side: true, dbOpt: true, muscles: 'Benen, billen',
    steps: ['Ga voor de onderste traptrede staan en houd de leuning vast.', 'Zet je hele rechtervoet op de trede.', 'Duw jezelf omhoog via je rechterbeen en zet je linkervoet erbij.', 'Stap rustig terug. Alle herhalingen, dan de andere kant.'], tip: 'Duw vanuit het bovenste been, niet afzetten met het onderste.', q: 'step up exercise stairs form' },
  singlebridge: { name: 'Bilbrug op één been', kind: 'reps', side: true, muscles: 'Billen, achterkant bovenbeen',
    steps: ['Lig op je rug, voeten plat, armen naast je lichaam.', 'Strek één been of til het met gebogen knie op.', 'Duw je heupen omhoog met het andere been.', 'Zak rustig. Alle herhalingen, dan de andere kant.'], tip: 'Houd je heupen recht, laat ze niet kantelen.', q: 'single leg glute bridge' },
  kickback: { name: 'Staand been naar achter', kind: 'reps', side: true, muscles: 'Billen',
    steps: ['Houd een stoel of muur vast en sta rechtop.', 'Breng één gestrekt been rustig naar achteren.', 'Knijp je bil aan zonder je rug hol te trekken.', 'Terug en herhalen. Daarna de andere kant.'], tip: 'Kleine beweging, groot effect.', q: 'standing glute kickback' },
  zijstap: { name: 'Staand been opzij heffen', kind: 'reps', side: true, muscles: 'Buitenkant heup, billen',
    steps: ['Houd een stoel of muur vast.', 'Til één gestrekt been rustig opzij.', 'Houd je bovenlichaam rechtop.', 'Laat langzaam zakken. Daarna de andere kant.'], tip: 'Tenen wijzen naar voren.', q: 'standing hip abduction' },
  liggendmars: { name: 'Liggend marcheren', kind: 'reps', muscles: 'Buik, rompstabiliteit',
    steps: ['Lig op je rug met gebogen knieën, voeten plat.', 'Druk je onderrug zacht tegen de vloer.', 'Til afwisselend één voet een stukje op en zet hem terug.', 'Elke kant telt als één herhaling.'], tip: 'Rustig en gecontroleerd; je onderrug blijft liggen.', q: 'supine marching core exercise' },
  hammer: { name: 'Hammer curl', kind: 'reps', db: true, muscles: 'Biceps, onderarmen',
    steps: ['Sta rechtop met een dumbbell in elke hand, handpalmen naar elkaar.', 'Houd je ellebogen bij je lichaam.', 'Buig je armen tot de dumbbells bij je schouders zijn.', 'Laat langzaam zakken.'], tip: 'Polsvriendelijke greep.', q: 'dumbbell hammer curl' },
  frontraise: { name: 'Voorwaarts heffen', kind: 'reps', db: true, muscles: 'Schouders',
    steps: ['Sta rechtop met de dumbbells voor je bovenbenen.', 'Til je armen gestrekt naar voren tot schouderhoogte.', 'Laat langzaam zakken.'], tip: 'Niet zwaaien; afwisselend links en rechts mag ook.', q: 'dumbbell front raise form' },
  wallangel: { name: 'Muurengel', kind: 'reps', muscles: 'Bovenrug, schouders, houding',
    steps: ['Sta met je rug en achterhoofd tegen een muur, voeten iets ervandaan.', 'Armen in een W-vorm tegen de muur.', 'Schuif je armen langs de muur omhoog naar een Y.', 'Schuif terug naar de W.'], tip: 'Ga zo ver als lukt zonder dat je rug loskomt.', q: 'wall angels exercise' },
  tricepsligg: { name: 'Liggende triceps extension', kind: 'reps', db: true, muscles: 'Achterkant bovenarm',
    steps: ['Lig op je rug, knieën gebogen, een dumbbell in elke hand boven je borst.', 'Buig alleen je ellebogen en laat de dumbbells naast je hoofd zakken.', 'Strek je armen weer.'], tip: 'Bovenarmen blijven stil; rug is volledig gesteund.', q: 'lying dumbbell tricep extension' },
  lopen: { name: 'Hardlopen', kind: 'time', muscles: 'Conditie',
    steps: ['Loop in een rustig tempo waarin je nog korte zinnen kunt praten.', 'Kleine, lichte passen; land onder je lichaam.', 'Ontspan je schouders en handen.'], tip: 'Te zwaar? Loop langzamer, niet harder.', q: 'beginner running form tips' },
  wandelen: { name: 'Stevig wandelen', kind: 'time', muscles: 'Conditie, herstel',
    steps: ['Wandel in een stevig tempo.', 'Zwaai je armen mee.', 'Gebruik dit om op adem te komen.'], tip: 'Wandelen is ook trainen.', q: 'brisk walking technique' }
};

const WARMUP = [['mars', 60], ['armcirkel', 30], ['heupcirkel', 30], ['beenzwaai', 40], ['stepjack', 60], ['squatreach', 45], ['hakbil', 45]];
const COOLDOWN = [['uitlopen', 60], ['str_quad', 50], ['str_ham', 50], ['str_kuit', 40], ['str_bil', 50], ['str_schouder', 30], ['adem', 40]];

const LADDERS = {
  circuit: [
    { work: 25, rest: 35, rounds: 2 }, { work: 30, rest: 30, rounds: 2 }, { work: 30, rest: 30, rounds: 3 },
    { work: 35, rest: 25, rounds: 3 }, { work: 40, rest: 20, rounds: 3 }, { work: 40, rest: 20, rounds: 4 },
    { work: 45, rest: 15, rounds: 4 }, { work: 45, rest: 15, rounds: 5 }
  ],
  hiit: [
    { work: 20, rest: 40, rounds: 3 }, { work: 25, rest: 35, rounds: 3 }, { work: 30, rest: 30, rounds: 3 },
    { work: 30, rest: 30, rounds: 4 }, { work: 35, rest: 25, rounds: 4 }, { work: 40, rest: 20, rounds: 4 },
    { work: 40, rest: 20, rounds: 5 }, { work: 45, rest: 15, rounds: 5 }
  ],
  finisher: [
    { work: 20, rest: 40, rounds: 2 }, { work: 30, rest: 30, rounds: 2 }, { work: 30, rest: 30, rounds: 3 },
    { work: 40, rest: 20, rounds: 3 }, { work: 40, rest: 20, rounds: 4 }
  ]
};

const RUN_LEVELS = [
  { run: 60, walk: 120, reps: 6 }, { run: 60, walk: 90, reps: 8 }, { run: 90, walk: 90, reps: 7 },
  { run: 120, walk: 90, reps: 6 }, { run: 150, walk: 90, reps: 5 }, { run: 180, walk: 90, reps: 5 },
  { run: 240, walk: 90, reps: 4 }, { run: 300, walk: 90, reps: 4 }, { run: 360, walk: 90, reps: 3 },
  { run: 480, walk: 120, reps: 3 }, { run: 600, walk: 120, reps: 2 }, { run: 720, walk: 120, reps: 2 },
  { run: 900, walk: 120, reps: 2 }, { run: 1200, walk: 0, reps: 1 }, { run: 1500, walk: 0, reps: 1 },
  { run: 1800, walk: 0, reps: 1 }
];

const EX_DEFAULTS = {
  squat: { reps: 10, sets: 2, min: 10, max: 15 }, sumo: { reps: 10, sets: 2, min: 10, max: 15 },
  lunge: { reps: 8, sets: 2, min: 8, max: 12 }, bridge: { reps: 12, sets: 2, min: 12, max: 20 },
  kuit: { reps: 15, sets: 2, min: 15, max: 25 }, zijbeen: { reps: 10, sets: 2, min: 10, max: 16 },
  clam: { reps: 12, sets: 2, min: 12, max: 20 }, deadbug: { reps: 10, sets: 2, min: 10, max: 16 },
  heeltaps: { reps: 16, sets: 2, min: 16, max: 30 }, zijplank: { sec: 20, sets: 2, min: 20, max: 45, rest: 45 },
  wallsit: { sec: 20, sets: 2, min: 20, max: 60, rest: 60 },
  curl: { reps: 10, sets: 2, min: 8, max: 14 }, press: { reps: 8, sets: 2, min: 8, max: 14 },
  lateral: { reps: 8, sets: 2, min: 8, max: 14 }, triceps: { reps: 10, sets: 2, min: 8, max: 14 },
  pullover: { reps: 10, sets: 2, min: 8, max: 14 }, floorpress: { reps: 10, sets: 2, min: 8, max: 14 },
  stoelsquat: { reps: 10, sets: 2, min: 10, max: 15 }, splitsquat: { reps: 8, sets: 2, min: 8, max: 12 },
  stepup: { reps: 8, sets: 2, min: 8, max: 12 }, singlebridge: { reps: 8, sets: 2, min: 8, max: 12 },
  kickback: { reps: 12, sets: 2, min: 12, max: 20 }, zijstap: { reps: 12, sets: 2, min: 12, max: 20 },
  liggendmars: { reps: 12, sets: 2, min: 12, max: 24 }, zijcrunch: { reps: 10, sets: 2, min: 10, max: 16 },
  hammer: { reps: 10, sets: 2, min: 8, max: 14 }, frontraise: { reps: 8, sets: 2, min: 8, max: 14 },
  wallangel: { reps: 8, sets: 2, min: 8, max: 15 }, tricepsligg: { reps: 10, sets: 2, min: 8, max: 14 }
};

const WORKOUTS = {
  A: { name: 'Conditiecircuit', short: 'A', color: 'coral',
    desc: 'Staand cardio-circuit zonder springen. Elke oefening een vaste tijd, daarna even rust.',
    blocks: [
      { type: 'check', title: 'Warming-up', items: WARMUP },
      { type: 'timed', title: 'Circuit', key: 'A1', ladder: 'circuit', roundRest: 60, ex: ['mars', 'squatreach', 'boksen', 'skater', 'kniecross', 'stepjack'] },
      { type: 'check', title: 'Afkoelen & rekken', items: COOLDOWN }
    ] },
  B: { name: 'Kracht & conditie', short: 'B', color: 'teal',
    desc: 'Benen, billen, armen en schouders met lichaamsgewicht en lichte dumbbells, met een korte cardio-afsluiter.',
    blocks: [
      { type: 'check', title: 'Warming-up', items: WARMUP },
      { type: 'sets', title: 'Kracht', rest: 60, trans: 90, ex: ['squat', 'lunge', 'bridge', 'press', 'pullover', 'curl', 'deadbug'] },
      { type: 'timed', title: 'Cardio-afsluiter', key: 'B2', ladder: 'finisher', roundRest: 30, optional: true, ex: ['boksen', 'shuffle', 'mars'] },
      { type: 'check', title: 'Afkoelen & rekken', items: COOLDOWN }
    ] },
  C: { name: 'HIIT & buik', short: 'C', color: 'plum',
    desc: 'Korte intervallen op hoog tempo (zonder springen), gevolgd door buik- en heupoefeningen op de grond.',
    blocks: [
      { type: 'check', title: 'Warming-up', items: WARMUP },
      { type: 'timed', title: 'HIIT', key: 'C1', ladder: 'hiit', roundRest: 60, ex: ['squatreach', 'hakbil', 'skater', 'voetjes'] },
      { type: 'sets', title: 'Buik, heupen & armen', rest: 45, trans: 90, ex: ['deadbug', 'heeltaps', 'zijplank', 'clam', 'zijbeen', 'sumo', 'lateral'] },
      { type: 'check', title: 'Afkoelen & rekken', items: COOLDOWN }
    ] },
  L: { name: 'Wandel-hardloop', short: 'L', color: 'sun',
    desc: 'Rustig opbouwen van wandelen naar 30 minuten hardlopen. Elke training: 5 min wandelen, afwisselend lopen en wandelen, 5 min uitwandelen.',
    blocks: [{ type: 'run' }, { type: 'check', title: 'Rekken', items: COOLDOWN.slice(1) }] }
};

const TIPS_TRAIN = [
  { t: 'Spierpijn of pijn?', b: 'Spierpijn (stijf, gevoelig, 1–3 dagen na de training) is normaal. Scherpe pijn in een gewricht, pijn die tijdens het bewegen erger wordt of pijn die na een paar dagen niet weg is: stoppen met die oefening en eventueel een fysiotherapeut vragen.' },
  { t: 'Rustig beginnen met hardlopen', b: 'Loop in een tempo waarin je nog korte zinnen kunt praten. Liever te langzaam dan te snel. Voer niet meer dan één stap tegelijk op, en herhaal een niveau gerust als het zwaar voelde.' },
  { t: 'Blessuregevoelig?', b: 'Goede hardloopschoenen maken veel verschil. Loop bij voorkeur op een zachte ondergrond (bospad, gravel), houd minstens één dag tussen twee looptrainingen en neem signalen van je lichaam serieus: in de app kun je na elke training "pijn/klachten" aangeven, dan stelt de app voor om een stapje terug te doen.' },
  { t: 'Warming-up overslaan?', b: 'Liever niet. Vier tot vijf minuten opwarmen maakt je gewrichten soepel en de training voelt daarna vaak lichter.' },
  { t: 'Twee keer per week is genoeg', b: 'Voor een beginner geeft twee keer per week al duidelijk resultaat. Consistentie is belangrijker dan intensiteit: liever acht weken lang twee keer dan twee weken lang vijf keer.' },
  { t: 'Wanneer zwaarder?', b: 'De app kijkt na elke training hoe het ging. Heb je alles gehaald en voelde het goed te doen, twee keer achter elkaar? Dan krijg je een voorstel om een stap zwaarder te gaan. Jij beslist of je het toepast.' }
];

const TIPS_FOOD = [
  { t: 'Eiwit bij elke maaltijd', b: 'Eiwit helpt bij herstel en spieropbouw en houdt je langer verzadigd. Makkelijke bronnen: kwark, Griekse yoghurt, eieren, kaas, cottage cheese, kip, peulvruchten en tofu.' },
  { t: 'Half bord groente', b: 'Vul de helft van je bord met groente of salade, een kwart met eiwit en een kwart met volkoren granen of aardappel. Diepvriesgroente is net zo goed en scheelt tijd.' },
  { t: 'Kies volkoren', b: 'Volkoren brood, pasta, havermout en zilvervliesrijst geven langer energie dan witte varianten; handig voor je conditie.' },
  { t: 'Voor en na het trainen', b: 'Train je binnen een uur na het eten, houd het licht (banaan, yoghurt). Na de training: iets met eiwit en koolhydraten, zoals kwark met fruit of een boterham met kaas en ei.' },
  { t: 'Drink genoeg', b: 'Anderhalf tot twee liter per dag, en wat extra rond het sporten. Water, thee en koffie tellen mee.' },
  { t: 'Afvallen zonder crashdieet', b: 'Kleine, vol te houden aanpassingen werken het best: minder frisdrank en alcohol, groter groentedeel, kleinere portie saus. Sla geen maaltijden over; dat leidt vaak tot snaaien. Kaas en romige gerechten passen er prima in, let alleen wat op de hoeveelheid.' },
  { t: 'Slaap telt mee', b: 'Wie goed slaapt, herstelt beter en heeft minder trek in snelle suikers. Probeer op vaste tijden naar bed te gaan.' },
  { t: 'Kruiden checken', b: 'Kant-en-klare kruidenmixen (taco, curry, shoarma) bevatten vaak koriander. In de recepten hier worden losse kruiden gebruikt. Let ook op worcestersaus en caesardressing: daar zit ansjovis in.' }
];

const MEALS = [
  { id: 'm1', cat: 'Ontbijt', name: 'Yoghurtbowl met havermout en pindakaas', min: 5,
    ing: ['200 g Griekse yoghurt of kwark', '3 el havermout', '1 banaan in plakjes', '1 el pindakaas', 'snufje kaneel'],
    steps: ['Schep de yoghurt in een kom.', 'Top met havermout, banaan en pindakaas.', 'Bestrooi met kaneel.'], why: 'Veel eiwit en langzame koolhydraten: lang verzadigd.' },
  { id: 'm2', cat: 'Ontbijt', name: 'Overnight oats met appel en kaneel', min: 5,
    ing: ['40 g havermout', '100 g kwark', '100 ml melk', '½ appel, geraspt', '1 tl honing', 'kaneel'],
    steps: ['Meng alles in een pot of bakje.', 'Zet afgedekt een nacht in de koelkast.', 'Roer door en eet koud, of 1 minuut in de magnetron.'], why: 'Klaar voor een drukke ochtend; vezels en eiwit.' },
  { id: 'm3', cat: 'Ontbijt', name: 'Roerei met spinazie en geitenkaas', min: 10,
    ing: ['2 eieren', 'handje spinazie', '30 g zachte geitenkaas', '1 volkoren boterham', 'peper en zout'],
    steps: ['Laat de spinazie slinken in een pan met een beetje olie.', 'Klop de eieren los en roer ze erdoor op laag vuur.', 'Verkruimel de geitenkaas erover.', 'Serveer op geroosterd volkorenbrood.'], why: 'Eiwitrijk en romig, met groente bij het ontbijt.' },
  { id: 'm4', cat: 'Ontbijt', name: 'Omelet met ham, paprika en kaas', min: 10,
    ing: ['2 eieren', '½ paprika in blokjes', '2 plakjes achterham', '30 g geraspte kaas', 'bieslook'],
    steps: ['Bak de paprika 2 minuten.', 'Giet de losgeklopte eieren erover.', 'Leg ham en kaas op de helft zodra de onderkant gestold is.', 'Vouw dubbel en bak nog even af.'], why: 'Snel, hartig en vult goed.' },
  { id: 'm5', cat: 'Ontbijt', name: 'Groene ontbijtsmoothie', min: 5,
    ing: ['1 banaan', 'handje spinazie', '2 el havermout', '1 el pindakaas', '250 ml melk'],
    steps: ['Doe alles in een blender.', 'Mix tot een gladde smoothie.'], why: 'Makkelijk mee te nemen; je proeft de spinazie niet.' },
  { id: 'm6', cat: 'Lunch', name: 'Wrap met kip, hummus en feta', min: 10,
    ing: ['1 volkoren wrap', '2 el hummus', '75 g gebakken kipreepjes', 'handje rucola', '30 g feta', 'komkommer in reepjes'],
    steps: ['Besmeer de wrap met hummus.', 'Beleg met kip, rucola, komkommer en feta.', 'Oprollen en doormidden snijden.'], why: 'Eiwit uit kip, feta en hummus.' },
  { id: 'm7', cat: 'Lunch', name: 'Griekse kikkererwtensalade', min: 10,
    ing: ['½ blik kikkererwten, afgespoeld', '½ komkommer', '6 cherrytomaatjes', '50 g feta', 'paar olijven', 'olijfolie, citroen, oregano'],
    steps: ['Snijd groente in stukjes.', 'Meng met kikkererwten, feta en olijven.', 'Maak aan met olijfolie, een scheut citroen en oregano.'], why: 'Vezels en plantaardig eiwit; goed voor te maken.' },
  { id: 'm8', cat: 'Lunch', name: 'Snelle tomaten-linzensoep', min: 15,
    ing: ['1 ui', '1 teen knoflook', '1 blik tomatenblokjes', '100 g rode linzen', '500 ml groentebouillon', '1 tl paprikapoeder', 'scheutje room of een el roomkaas'],
    steps: ['Fruit ui en knoflook.', 'Voeg tomaten, linzen, bouillon en paprikapoeder toe.', 'Kook 12 minuten tot de linzen zacht zijn.', 'Pureer en roer de room erdoor.'], why: 'Romig, vult goed en is 2–3 dagen houdbaar in de koelkast.' },
  { id: 'm9', cat: 'Lunch', name: 'Couscous met halloumi en groenten', min: 15,
    ing: ['60 g volkoren couscous', '75 g halloumi in plakken', '½ courgette', '½ paprika', 'citroen, olijfolie, munt of peterselie'],
    steps: ['Wel de couscous met heet water (5 min).', 'Grill of bak groenten en halloumi goudbruin.', 'Meng met couscous, citroen en olijfolie.', 'Top met verse munt of peterselie.'], why: 'Kaas als eiwitbron, veel groente.' },
  { id: 'm10', cat: 'Lunch', name: 'Eiersalade op roggebrood', min: 12,
    ing: ['2 gekookte eieren', '2 el Griekse yoghurt', '1 tl mosterd', 'bieslook', '2 sneetjes roggebrood', 'plakjes tomaat'],
    steps: ['Prak de eieren met yoghurt en mosterd.', 'Breng op smaak met bieslook, peper en zout.', 'Beleg het roggebrood met tomaat en eiersalade.'], why: 'Yoghurt i.p.v. mayonaise: romig en lichter.' },
  { id: 'm11', cat: 'Lunch', name: 'Caprese pastasalade', min: 15,
    ing: ['70 g volkoren pasta', '1 bol mozzarella', '8 cherrytomaatjes', 'handje basilicum', '1 el pesto', 'handje rucola'],
    steps: ['Kook de pasta en spoel koud af.', 'Meng met pesto, gehalveerde tomaatjes en stukjes mozzarella.', 'Schep rucola en basilicum erdoor.'], why: 'Makkelijk mee te nemen naar werk.' },
  { id: 'm12', cat: 'Diner', name: 'Romige kippasta met spinazie', min: 20,
    ing: ['75 g volkoren pasta', '125 g kipfilet in blokjes', '2 el kruidenroomkaas', '2 handen spinazie', '1 teen knoflook', '6 cherrytomaatjes', 'geraspte Parmezaanse kaas'],
    steps: ['Kook de pasta.', 'Bak de kip met knoflook gaar.', 'Voeg tomaatjes en spinazie toe en laat slinken.', 'Roer roomkaas en een scheutje pastawater erdoor.', 'Meng met pasta en bestrooi met Parmezaan.'], why: 'Romig maar in balans, met flink wat groente.' },
  { id: 'm13', cat: 'Diner', name: 'Ovenschotel kip, zoete aardappel en feta', min: 30,
    ing: ['1 zoete aardappel in blokjes', '1 paprika', '1 rode ui', '125 g kipdijfilet', '50 g feta', 'olijfolie, paprikapoeder, knoflookpoeder, tijm'],
    steps: ['Verwarm de oven op 200 °C.', 'Hussel alles behalve de feta met olie en kruiden op een bakplaat.', '25 minuten roosteren.', 'Verkruimel de feta erover en nog 5 minuten.'], why: 'Eén bakplaat, weinig afwas, veel voedingsstoffen.' },
  { id: 'm14', cat: 'Diner', name: 'Burrito bowl met gehakt en bonen', min: 20,
    ing: ['100 g mager rundergehakt', '½ blik zwarte of kidneybonen', '½ blikje mais', '1 paprika', '50 g zilvervliesrijst', '1 tl paprikapoeder, ½ tl komijn, oregano, knoflook', 'geraspte kaas, zure room'],
    steps: ['Kook de rijst.', 'Rul het gehakt met de kruiden.', 'Bak paprika mee en voeg bonen en mais toe.', 'Serveer op rijst met kaas en een lepel zure room.'], why: 'Losse kruiden i.p.v. tacomix (geen koriander).' },
  { id: 'm15', cat: 'Diner', name: 'Roerbak kip met broccoli en cashew', min: 20,
    ing: ['125 g kipfilet', '1 kleine broccoli', '1 rode paprika', 'handje cashewnoten', '2 el sojasaus', '1 tl geraspte gember', '1 teen knoflook', '60 g mie of rijst'],
    steps: ['Kook de mie of rijst.', 'Roerbak de kip goudbruin.', 'Voeg broccoli, paprika, gember en knoflook toe; 4 minuten roerbakken.', 'Blus af met sojasaus en schep de cashews erdoor.'], why: 'Snel, groenterijk en veel eiwit.' },
  { id: 'm16', cat: 'Diner', name: 'Shakshuka met feta', min: 20,
    ing: ['1 ui', '1 paprika', '1 blik tomatenblokjes', '3 eieren', '50 g feta', '1 tl komijn, 1 tl paprikapoeder', 'peterselie', 'volkorenbrood'],
    steps: ['Fruit ui en paprika zacht.', 'Voeg kruiden en tomaten toe; 8 minuten sudderen.', 'Maak kuiltjes en breek de eieren erin.', 'Deksel erop, 6 minuten op laag vuur.', 'Top met feta en peterselie.'], why: 'Vegetarisch, eiwitrijk en goedkoop.' },
  { id: 'm17', cat: 'Diner', name: 'Orzo met kip, erwten en Parmezaan', min: 20,
    ing: ['75 g orzo', '125 g kipfilet', '100 g doperwten (diepvries)', '400 ml kippenbouillon', '30 g Parmezaanse kaas', 'rasp van ½ citroen'],
    steps: ['Bak de kip in blokjes en haal uit de pan.', 'Rooster de orzo kort in dezelfde pan.', 'Voeg bouillon toe en kook 10 minuten al roerend.', 'Roer erwten, kip, Parmezaan en citroenrasp erdoor.'], why: 'Romig als risotto, maar in 20 minuten klaar.' },
  { id: 'm18', cat: 'Diner', name: 'Romige linzendahl', min: 25,
    ing: ['1 ui', '2 tenen knoflook', '1 tl gember', '1 tl kurkuma, 1 tl komijn, ½ tl paprikapoeder', '100 g rode linzen', '200 ml kokosmelk', '200 ml bouillon', 'spinazie, naanbrood of rijst'],
    steps: ['Fruit ui, knoflook en gember.', 'Voeg de losse kruiden toe en bak 1 minuut.', 'Voeg linzen, kokosmelk en bouillon toe; 15 minuten koken.', 'Roer spinazie erdoor en serveer met rijst of naan.'], why: 'Zonder kerriepoeder of garam masala, dus zonder koriander.' },
  { id: 'm19', cat: 'Diner', name: 'Kipgehaktballetjes in tomatensaus met mozzarella', min: 25,
    ing: ['150 g kipgehakt', '1 el paneermeel', '1 teen knoflook', '½ pak passata (250 ml)', 'Italiaanse kruiden', '½ bol mozzarella', '75 g volkoren spaghetti'],
    steps: ['Draai kleine balletjes van gehakt, paneermeel en knoflook.', 'Bak ze rondom bruin.', 'Voeg passata en kruiden toe; 10 minuten sudderen.', 'Leg er plakjes mozzarella op tot ze smelten.', 'Serveer met spaghetti.'], why: 'Comfortfood met veel eiwit.' },
  { id: 'm20', cat: 'Diner', name: 'Frittata met courgette en feta', min: 20,
    ing: ['4 eieren', '1 courgette in plakjes', '1 rode ui', '50 g feta', 'handje spinazie', 'tijm'],
    steps: ['Bak ui en courgette 5 minuten in een ovenvaste pan.', 'Voeg spinazie toe.', 'Giet de losgeklopte eieren erover en verkruimel de feta.', '10 minuten in de oven op 190 °C of met deksel op laag vuur.'], why: 'Ook koud lekker als lunch de volgende dag.' },
  { id: 'm21', cat: 'Snack', name: 'Cottage cheese met komkommer en tomaat', min: 3,
    ing: ['150 g cottage cheese', '¼ komkommer', 'paar tomaatjes', 'peper, bieslook'],
    steps: ['Snijd de groente in blokjes.', 'Meng met cottage cheese en kruiden.'], why: 'Veel eiwit, weinig calorieën.' },
  { id: 'm22', cat: 'Snack', name: 'Appel met pindakaas', min: 2,
    ing: ['1 appel', '1 el pindakaas'], steps: ['Snijd de appel in partjes en dip in pindakaas.'], why: 'Zoet, knapperig en verzadigend.' },
  { id: 'm23', cat: 'Snack', name: 'Hummus met groentesticks', min: 5,
    ing: ['3 el hummus', 'wortel, komkommer, paprika in reepjes'], steps: ['Snijd de groente in sticks.', 'Dippen maar.'], why: 'Extra groente op een makkelijke manier.' },
  { id: 'm24', cat: 'Snack', name: 'Blokjes kaas met druiven en noten', min: 2,
    ing: ['30 g kaas (bijv. belegen of oude)', 'handje druiven', 'handje ongezouten noten'], steps: ['In een bakje doen, klaar.'], why: 'Kaas mag, prima snack in een kleine portie.' },
  { id: 'm25', cat: 'Na training', name: 'Chocolade-herstelshake', min: 5,
    ing: ['250 ml (halfvolle) melk', '100 g kwark', '1 banaan', '1 el cacaopoeder', '1 tl honing'],
    steps: ['Alles in de blender.', 'Mixen en direct opdrinken.'], why: 'Eiwit en koolhydraten voor herstel.' },
  { id: 'm26', cat: 'Na training', name: 'Boterham met kaas en gekookt ei', min: 10,
    ing: ['2 volkoren boterhammen', '1 plak kaas', '1 gekookt ei', 'tomaat of komkommer'],
    steps: ['Kook het ei 8 minuten.', 'Beleg de boterhammen met kaas, ei en groente.'], why: 'Simpel en compleet na het sporten.' },
  { id: 'm27', cat: 'Na training', name: 'Kwark met fruit en granola', min: 3,
    ing: ['200 g magere kwark', 'handje (diepvries)fruit', '2 el granola'], steps: ['Schep alles in een kom.'], why: 'Snel eiwit binnen, lekker fris.' }
];

const ALTS = {
  mars: [['hakbil', 'Zelfde intensiteit, andere spieren'], ['voetjes', 'Sneller, kleine pasjes'], ['trede', 'Als je een trap hebt']],
  stepjack: [['mars', 'Nog rustiger voor knieën en heupen'], ['zijtik', 'Zonder armen boven het hoofd'], ['shuffle', 'Meer benen en billen']],
  boksen: [['kniecross', 'Meer buik, minder schouders'], ['mars', 'Als je schouders moe zijn'], ['stepjack', 'Hele lichaam']],
  skater: [['shuffle', 'Minder draaien in de knie'], ['zijtik', 'Rustigere variant'], ['stepjack', 'Minder balans nodig']],
  kniecross: [['zijcrunch', 'Meer zijkant van de buik'], ['mars', 'Rustiger'], ['boksen', 'Meer bovenlichaam']],
  hakbil: [['mars', 'Rustiger'], ['voetjes', 'Sneller'], ['zijtik', 'Zijwaarts']],
  squatreach: [['stoelsquat', 'Kniesparend, met een stoel'], ['trede', 'Als je een trap hebt'], ['mars', 'Geen squat, wel cardio']],
  shuffle: [['skater', 'Meer billen'], ['zijtik', 'Rustiger'], ['stepjack', 'Minder zijwaarts']],
  voetjes: [['mars', 'Rustiger voor de kuiten'], ['hakbil', 'Minder kuitbelasting'], ['boksen', 'Voeten rust, armen werken']],
  squat: [['stoelsquat', 'Kniesparend, met steun van een stoel'], ['sumo', 'Bredere stand'], ['wallsit', 'Vasthouden tegen de muur']],
  sumo: [['squat', 'Standaard squat'], ['stoelsquat', 'Kniesparend'], ['zijstap', 'Staand, zonder door de knieën']],
  lunge: [['splitsquat', 'Stabieler: je voeten blijven staan'], ['stepup', 'Op de trap, minder knieduw'], ['bridge', 'Geen kniebelasting']],
  bridge: [['singlebridge', 'Zwaarder, per been'], ['kickback', 'Staand, geen grondwerk'], ['clam', 'Lichter, meer heup']],
  zijbeen: [['zijstap', 'Staand in plaats van liggend'], ['clam', 'Kleinere beweging'], ['kickback', 'Andere kant van de bil']],
  clam: [['zijbeen', 'Iets zwaarder'], ['zijstap', 'Staand'], ['bridge', 'Meer bilspieren']],
  deadbug: [['liggendmars', 'Makkelijker, zelfde idee'], ['heeltaps', 'Meer schuine buikspieren'], ['zijcrunch', 'Staand, geen grondwerk']],
  heeltaps: [['deadbug', 'Rugvriendelijk en stabiel'], ['liggendmars', 'Rustiger voor de nek'], ['zijcrunch', 'Staand']],
  zijplank: [['liggendmars', 'Geen steun op de arm'], ['deadbug', 'Liggend op je rug'], ['zijcrunch', 'Staand']],
  wallsit: [['squat', 'Bewegen in plaats van vasthouden'], ['stoelsquat', 'Kniesparend']],
  kuit: [['stepup', 'Meer bovenbeen erbij'], ['voetjes', 'Als cardio']],
  curl: [['hammer', 'Andere greep, polsvriendelijker'], ['frontraise', 'Meer schouders']],
  press: [['frontraise', 'Lichter voor de schouders'], ['lateral', 'Zijkant van de schouders'], ['floorpress', 'Liggend, rug volledig gesteund']],
  lateral: [['frontraise', 'Voorkant van de schouders'], ['press', 'Duwbeweging'], ['wallangel', 'Zonder gewicht']],
  pullover: [['wallangel', 'Zonder gewicht, goed voor je houding'], ['floorpress', 'Borst in plaats van rug'], ['tricepsligg', 'Achterkant bovenarm']],
  floorpress: [['pullover', 'Rug en borst'], ['press', 'Staand of zittend']],
  triceps: [['tricepsligg', 'Liggend, rug gesteund'], ['press', 'Samen met de schouders']]
};

const NUTRI = {
  m1: [20, 520], m2: [18, 320], m3: [23, 375], m4: [28, 365], m5: [16, 395], m6: [35, 470], m7: [16, 410],
  m8: [13, 325, 2], m9: [24, 570], m10: [21, 370], m11: [32, 645], m12: [48, 615], m13: [38, 725], m14: [40, 700],
  m15: [47, 665], m16: [38, 700], m17: [53, 670], m18: [15, 430, 2], m19: [52, 785], m20: [20, 315, 2],
  m21: [17, 170], m22: [4, 175], m23: [4, 175], m24: [12, 320], m25: [21, 320], m26: [19, 330], m27: [21, 270]
};
MEALS.forEach(m => { const n = NUTRI[m.id]; if (n) { m.p = n[0]; m.kcal = n[1]; if (n[2]) m.serv = n[2]; } });

const QUICK = [
  { name: 'Magere kwark (250 g)', p: 22, kcal: 145 }, { name: 'Griekse yoghurt (150 g)', p: 9, kcal: 180 },
  { name: 'Cottage cheese (150 g)', p: 17, kcal: 150 }, { name: 'Ei', p: 7, kcal: 80 },
  { name: 'Plak kaas', p: 5, kcal: 75 }, { name: 'Volkoren boterham', p: 4, kcal: 85 },
  { name: 'Kipfilet (100 g)', p: 30, kcal: 150 }, { name: 'Glas halfvolle melk', p: 9, kcal: 115 },
  { name: 'Handje noten (25 g)', p: 5, kcal: 155 }, { name: 'Pindakaas (1 el)', p: 4, kcal: 95 },
  { name: 'Banaan', p: 1, kcal: 105 }, { name: 'Appel', p: 0, kcal: 80 }
];

const ACTIVITY = [
  [1.2, 'Zittend', 'Vooral zittend werk, weinig beweging'],
  [1.375, 'Licht actief', 'Wat wandelen/fietsen, 1–3× per week sporten'],
  [1.55, 'Gemiddeld actief', 'Veel op de been of 3–5× per week sporten'],
  [1.725, 'Zeer actief', 'Fysiek werk of bijna dagelijks sporten']
];
const GOALS = [[0, 'Gewicht behouden (fitter worden)'], [-300, 'Rustig afvallen (± 0,25 kg/week)'], [-500, 'Afvallen (± 0,5 kg/week)']];
